blueprint:
  name: Area Presence Automation
  description: 'Manage area presence and occupancy states based on sensor input and delay.'
  domain: automation
  input:
    area:
      name: Area
      selector:
        area: {}
    area_presence_id:
      name: Area Presence ID
      selector:
        entity:
          domain: input_select
    area_occupancy_id:
      name: Area Occupancy ID
      selector:
        entity:
          domain: input_boolean
    area_idle_time_id:
      name: Area Idle Time ID
      description: A delay time when absence is detected and when the area is considered to be unoccupied.
      selector:
        entity:
          domain: input_number
    sensor_entity:
      name: Area Occupancy Sensor
      description: The occupancy sensor that detect presence on this area
      selector:
        entity:
          domain: binary_sensor
  trigger:
    - platform: state
      entity_id: !input 'sensor_entity'
  variables:
    area_presence_id: !input 'area_presence_id'
    area_occupancy_id: !input 'area_occupancy_id'
    area_idle_time_id: !input 'area_idle_time_id'
    sensor_state: '{{ trigger.to_state.state }}'
  condition: []
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ sensor_state == 'on' }}"
          sequence:
            - service: input_boolean.turn_on
              data:
                entity_id: !input 'area_occupancy_id'
            - service: input_select.select_option
              data:
                entity_id: !input 'area_presence_id'
                option: 'presence'
        - conditions:
            - condition: template
              value_template: "{{ sensor_state == 'off' }}"
          sequence:
            - service: input_boolean.turn_off
              data:
                entity_id: !input 'area_occupancy_id'
    - delay: '{{ states(area_idle_time_id) | int }}'
    - choose:
        - conditions:
            - condition: state
              entity_id: !input 'area_presence_id'
              state: 'idle'
          sequence:
            - service: input_select.select_option
              data:
                entity_id: !input 'area_presence_id'
                option: 'idle'
            - service: input_boolean.turn_off
              data:
                entity_id: !input 'area_occupancy_id'
        - conditions:
            - condition: state
              entity_id: !input 'area_presence_id'
              state: 'absence'
          sequence:
            - service: input_select.select_option
              data:
                entity_id: !input 'area_presence_id'
                option: 'absence'
            - service: input_boolean.turn_off
              data:
                entity_id: !input 'area_occupancy_id'
