blueprint:
  name: Area Presence Management
  description: Blueprint for managing area presence based on occupancy sensors.
  domain: automation
  input:
    area:
      name: Area
      description: Name of the area
      selector:
        text:
          multiline: false
    occupancy_sensor:
      name: Occupancy Sensor
      description: Occupancy sensor entity - The sensor that checks the are occupancy
      selector:
        entity:
          domain: binary_sensor
    presence_input:
      name: Area Presence Input
      description: Area presence input select entity
      selector:
        entity:
          domain: input_select
    idle_time_input:
      name: Area Idle Time Input
      description: Area idle time input number entity - The helper entity that defines the time before the status is changed to absence
      selector:
        entity:
          domain: input_number
    occupancy_input:
      name: Area Occupancy Input
      description: Area occupancy input boolean entity
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    to: 'on'
  - platform: state
    entity_id: !input occupancy_sensor
    to: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input occupancy_sensor
            state: 'on'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'presence'
      - conditions:
          - condition: state
            entity_id: !input occupancy_sensor
            state: 'off'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'absence'
          - delay:
              seconds: '{{ states(!input idle_time_input) | int }}'
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'idle'
      - conditions:
          - condition: state
            entity_id: !input hallway_sensor
            state: 'on'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'presence'
      - conditions:
          - condition: state
            entity_id: !input hallway_sensor
            state: 'off'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'absence'
      - conditions:
          - condition: state
            entity_id: !input lobby_sensor
            state: 'on'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'presence'
      - conditions:
          - condition: state
            entity_id: !input lobby_sensor
            state: 'off'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input occupancy_input
          - service: input_select.select_option
            target:
              entity_id: !input presence_input
            data:
              option: 'absence'
    default: []
